## The Background

In classical cryptography, the **Hill cipher** is a polygraphic substitution cipher based on matrix multiplications under a certain modulo (normally 26 for alphabet). Please refer [wikipedia](https://en.wikipedia.org/wiki/Hill_cipher) for the detail. The most important theorem of Hill cipher is as follows:

For any given matrix A, there exists a matrix B satisfies ```AB = BA = E``` iff. ```det(A)``` must not have any common factors with the modular base. Here **det(A)** refers to the determinant of matrix A.

In our case where the modular base equals **3**, we have:

### Theorem 1
For any given matrix A, there exists a matrix B satisfies ```AB = BA = E``` iff. ```det(A) | 3 > 0```.

Also, we can compute B from A by ```B = (1/det(A)) * adj(A) | 3 = det(A) * adj(A) | 3```, where adj(A) is the adjoint matrix of A. Note that if det(A) is 2, we have 1/det(A) equals 2 under modulo 3, and the same holds when det(A) is 1.

To demonstrate, we first define a matrix A, and compute det(A)

In [1]:
import numpy as np
from matrix import Matrix

A = Matrix(idx=1024)
int(np.linalg.det(A.m))

2

Then we get B from the adjoint matrix of A

In [2]:
def pair(a):
    a = a.astype(int)
    A = a[1][1] * a[2][2] - a[1][2] * a[2][1]
    B = -(a[0][1] * a[2][2] - a[0][2] * a[2][1])
    C = a[0][1] * a[1][2] - a[0][2] * a[1][1]
    D = -(a[1][0] * a[2][2] - a[1][2] * a[2][0])
    E = a[0][0] * a[2][2] - a[0][2] * a[2][0]
    F = -(a[0][0] * a[1][2] - a[0][2] * a[1][0])
    G = a[1][0] * a[2][1] - a[1][1] * a[2][0]
    H = -(a[0][0] * a[2][1] - a[0][1] * a[2][0])
    I = a[0][0] * a[1][1] - a[0][1] * a[1][0]

    b = np.array([[A, B, C],
                  [D, E, F],
                  [G, H, I]])

    b = b * int(np.linalg.det(a))
    b = b % 3
    return Matrix(m=b)

B = pair(A.m)
B

array([[0, 0, 1],
       [2, 2, 2],
       [0, 1, 2]])

and check the result

In [3]:
A * B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
B * A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Next, we compute det(X) for any matrix X in the scope

In [5]:
import pandas as pd

N = 19683
res = []
for i in range(N):
    d = int(np.linalg.det(Matrix(idx=i).m)) % 3
    res.append({
        'idx': i,
        'det': d
    })
df = pd.DataFrame(res)
df['det'].value_counts()

0    7925
1    5880
2    5878
Name: det, dtype: int64

This means we have **5879** pairs of **Hill cipher** matrices.