## The Background

In classical cryptography, the **Hill cipher** is a polygraphic substitution cipher based on matrix multiplications under a certain modulo (normally 26 for alphabet). Please refer [wikipedia](https://en.wikipedia.org/wiki/Hill_cipher) for the detail. The most important theorem of Hill cipher is as follows:

For any given matrix A, there exists a matrix B satisfies ```AB = BA = E``` iff. ```det(A)``` must not have any common factors with the modular base. Here **det(A)** refers to the determinant of matrix A.

In our case where the modular base equals **3**, we have:

### Theorem 1
For any given matrix A, there exists a matrix B satisfies ```AB = BA = E``` iff. ```det(A) | 3 > 0```.

Also, we can compute B from A by ```B = (1/det(A)) * adj(A) | 3 = det(A) * adj(A) | 3```, where adj(A) is the adjoint matrix of A. Note that if det(A) is 2, we have 1/det(A) equals 2 under modulo 3, and the same holds when det(A) is 1.

To demonstrate, we first define a matrix A, and compute det(A)

In [1]:
import numpy as np
from matrix import Matrix

A = Matrix(idx=1024)
int(np.linalg.det(A.m))

2

Then we get B from the adjoint matrix of A

In [6]:
B = A.inverse()
B

array([[0, 0, 1],
       [2, 2, 2],
       [0, 1, 2]], dtype=uint8)

and check the result

In [7]:
A * B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [8]:
B * A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

Next, we compute det(X) for any matrix X in the scope

In [9]:
import pandas as pd

N = 19683
res = []
for i in range(N):
    d = int(np.linalg.det(Matrix(idx=i).m)) % 3
    res.append({
        'idx': i,
        'det': d
    })
df = pd.DataFrame(res)
df['det'].value_counts()

0    7925
1    5880
2    5878
Name: det, dtype: int64

This means we have **5879** pairs of **Hill cipher** matrices.

In [20]:
det_1 = [i['idx'] for i in res if i['det'] == 1]
det_2 = [i['idx'] for i in res if i['det'] == 2]
print(len(det_1), len(det_2))

5880 5878


In [23]:
self_1 = [idx for idx in det_1 if Matrix(idx).inverse() == Matrix(idx)]
self_2 = [idx for idx in det_2 if Matrix(idx).inverse() == Matrix(idx)]
print(len(self_1), len(self_2))

101 115


In [27]:
A = Matrix(self_1[80])
print(A)
A_inv = A.inverse()
print(A_inv)
print(A * 

[[1 0 0]
 [1 2 0]
 [1 0 2]]
[[1 0 0]
 [1 2 0]
 [1 0 2]]


Those involutory matrices (self-inverse), i.e. `inv(A) = A`